### ISSUE TITLE
Enhanced Memory Metrics

### ISSUE THREAD

**Issue by bdarfler** [etsy/statsd-jvm-profiler#17]
Hello all. I'm a big user of NewRelic but I'm also interested in getting a lot of the JVM stats it provides into a more open metrics solution (graphite/influxdb/cloudwatch). This project exposes some of those metrics but there are a few pieces that are missing.

First and easiest would be class (un)loading tracking which an be accessed via http://docs.oracle.com/javase/7/docs/api/java/lang/management/ClassLoadingMXBean.html

Second and a bit more involved but also a bit more valuable would be memory pool tracking (old gen, eden, survivor) which I think can be accessed via http://docs.oracle.com/javase/7/docs/api/java/lang/management/MemoryPoolMXBean.html

Would these additions be valuable to this tool and in keeping with its vision? I wanted to ask before jumping in on any implementation work.

**Comment by ajsquared** [comment]
Yes, those would absolutely be valuable.  Thanks for your interest in contributing!
