### ISSUE TITLE
Support Disabling Built-In Metrics

### ISSUE THREAD

**Issue by ajsquared** [etsy/statsd-jvm-profiler#2]
Allow disabling either the memory or CPU metrics.

**Comment by otisg** [comment]
I think the suggestion in comments on https://codeascraft.com/2015/01/14/introducing-statsd-jvm-profiler-a-jvm-profiler-for-hadoop was really about being able to turn CPU profiling on/off dynamically, at run-time, on demand.  I think this commit doesn't implement that.

**Comment by ajsquared** [comment]
I had also gotten some requests via email for what this commit does implement.  That said, being able to turn it off at runtime is a great idea as well: https://github.com/etsy/statsd-jvm-profiler/issues/4
