### ISSUE TITLE
Problems with dashboard.

### ISSUE THREAD

**Issue by ibobak** [etsy/statsd-jvm-profiler#26]
Andrew,

there is one more issue with the dashboard. Here is the stacktrace - see below.
Feel free to ask me any data that you might need (e.g. to send you the backup of InfluxDB or anything like that).  Just give me instructions how to give it to you. 

Also feel free to give me any debug scripts to temporarily place instead of normal ones (to dump my data on the screen - I will paste it here).

Thanks.

GET /scripts/bootstrap.min.js 304 3.740 ms - -
GET /css/style.css 200 430.211 ms - -
/opt/influxdb-dashboard/public/scripts/influxdb.js:48
	var series = seriesNames[0];
	                        ^
TypeError: Cannot read property '0' of undefined
    at /opt/influxdb-dashboard/public/scripts/influxdb.js:48:26
    at /opt/influxdb-dashboard/node_modules/influx/index.js:181:14
    at /opt/influxdb-dashboard/node_modules/influx/index.js:64:14
    at InfluxRequest._request (/opt/influxdb-dashboard/node_modules/influx/lib/InfluxRequest.js:97:12)
    at InfluxRequest._parseCallback (/opt/influxdb-dashboard/node_modules/influx/lib/InfluxRequest.js:115:19)
    at Request._callback (/opt/influxdb-dashboard/node_modules/influx/lib/InfluxRequest.js:107:10)
    at self.callback (/opt/influxdb-dashboard/node_modules/influx/node_modules/request/request.js:197:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/opt/influxdb-dashboard/node_modules/influx/node_modules/request/request.js:854:8)
    at ClientRequest.emit (events.js:107:17)

**Comment by ajsquared** [comment]
What version of InfluxDB and statsd-jvm-profiler are you using?

**Comment by ibobak** [comment]
profiler - 0.8.3  (made git clone 10 hours ago and built it).
influxdb - 0.9.2-rc1   (installed using instruction from https://influxdb.com/download/index.html)
OS = CentOS 6.6

the reason of using the last influxdb was the bug https://github.com/influxdb/influxdb/issues/3222 with stable 0.9.1, but frankly speaking in  0.9.2-rc1 it remains.

**Comment by ajsquared** [comment]
I've only tested the profiler with InfluxDB 0.9.1.  Are you able to try that version?

If that doesn't work out, can you send me your dashboard-config.json file, the arguments given to the profiler when you used it, and the output of running `SHOW SERIES` on the database where the profiler writes its data?

**Comment by ibobak** [comment]
Andrew, 

here https://drive.google.com/file/d/0B3DMXMfcPWF3SXo3ZG9hWGNEOTA/view
is a document with detailed configuration and description of what I am doing and what I am getting.  I am using the newest dashboard (just pulled it). 

Please, help. Thank you in advance.

Regards,
Ihor

**Comment by ajsquared** [comment]
The error in your original comment happens when the dashboard queries for the `heap.total.max` measurement.  That metric was selected somewhat arbitrarily, but it should always be present and allows for a quick query to get all the valid tag values to populate those initial dropdowns.

It ultimately runs the query `show series from "heap.total.max"`.  Can you run that and show me the results?

**Comment by ibobak** [comment]
![2015-07-21 21_03_47-win7 running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/8807043/8808577/15374084-2fec-11e5-8043-f29caa7e304b.png)

**Comment by ibobak** [comment]
oh.... sorry -  the original message I posted from home.  it was a problem at home machine.  I will be there in an hour and will post you what was there.

**Comment by ibobak** [comment]
I am sorry if I confused you. I am little bit tired after 16 hours of work every day.

So, in general there are two things:
1) at home (with not a mapreduce job)  I am getting problem "Cannot read property '0' of undefined" in the dashboard
2) at work (with a mapreduce job)  I am getting the problem that the dashboard is empry (doesn't allow to select values for tags and build the Flame chart) - here is the screenshot:
 https://drive.google.com/file/d/0B3DMXMfcPWF3SXo3ZG9hWGNEOTA/view

**Comment by ajsquared** [comment]
Is this still a problem you're having after the changes you've made to deal with the OOM issues?

**Comment by ajsquared** [comment]
Let me know if you're still having any issues with this.
