### ISSUE TITLE
Upgrading VertX to 3.x makes statsd-jvm-profiler require 1.8 JVM

### ISSUE THREAD

**Issue by Ikariusrb** [etsy/statsd-jvm-profiler#41]
Not sure if you were aware of this, but the 3.x series of the vertx libraries are java 1.8- and I don't think many hadoop clusters are being run under JVM 1.8. Despite your pom specifying a maven-compiler-plugin target  of 1.7, the vertx artifact that gets pulled in is 1.8 only, and will bomb any 1.7 JVM.  In order to avoid trying replacement of the JVMs for my hadoop nodes, I was able to recompile statsd-jvm-profiler by cloning the repo and reverting the commit that upgraded vertx, but I thought you might want to be aware of this issue.

**Comment by ajsquared** [comment]
Thanks for the report, the intent was not to drop support for Java 7.  I'll back out that upgrade for now.

**Comment by ajsquared** [comment]
I've made a new release that downgrades to the previous version of Vertx to fix this.
